### ISSUE TITLE
ルートの第２項目が無効になっていない

### ISSUE THREAD

**Issue by Naoto-raimi** [DevGosugi/git-boot-camp-20181130-work1#5]
## 操作手順
* 計算法で√を選択すると
* 第一項目と第２項目両方が有効になっている

## 本来の想定
* √を選択したら
* 第二項目を無効になってほしい

**Comment by A-Nagamachi** [comment]
ルートの計算時に第二項目が無効になっていることを確認した

**Comment by JhonFuji** [comment]
ルートを選択したら第２項目が無効になった。
